# Add to vault
---
{{ "{{" }} with secret "kv/{{cookiecutter.application_name}}?version=4" {{ "}}" }}
ALLOWED_HOSTS:
- '*'
BACKEND_SERVICE_EDX_OAUTH2_KEY: x03VTXF7XgOerzJE4vp8CN69ats3mCqovBDiTveo
BACKEND_SERVICE_EDX_OAUTH2_PROVIDER_URL: https://courses.stage.edx.org/oauth2
BACKEND_SERVICE_EDX_OAUTH2_SECRET: '{{ "{{" }} .Data.data.BACKEND_SERVICE_EDX_OAUTH2_SECRET {{ "}}" }}'
CACHES:
  default:
    BACKEND: django.core.cache.backends.memcached.MemcachedCache
    KEY_PREFIX: {{cookiecutter.application_name}}
    LOCATION:
    - stage-{{cookiecutter.application_name}}.6sxrym.0001.use1.cache.amazonaws.com
    - stage-{{cookiecutter.application_name}}.6sxrym.0002.use1.cache.amazonaws.com
CSRF_COOKIE_SECURE: true
DATABASES:
  default:
    ATOMIC_REQUESTS: false
    CONN_MAX_AGE: 60
    ENGINE: django.db.backends.mysql
    HOST: stage-edx-{{cookiecutter.application_name}}-rds.edx.org
    NAME: {{cookiecutter.application_name}}
    OPTIONS:
      connect_timeout: 10
      init_command: SET sql_mode='STRICT_TRANS_TABLES'
      PASSWORD: '{{ "{{" }} .Data.data.DATABASE_DEFAULT_PASSWORD {{ "}}" }}'
    PORT: '3306'
    USER: {{cookiecutter.application_name}}001
EDX_DRF_EXTENSIONS:
  OAUTH2_USER_INFO_URL: https://courses.stage.edx.org/oauth2/user_info
JWT_AUTH:
  JWT_AUTH_COOKIE_HEADER_PAYLOAD: stage-edx-jwt-cookie-header-payload
  JWT_AUTH_COOKIE_SIGNATURE: stage-edx-jwt-cookie-signature
  JWT_AUTH_REFRESH_COOKIE: stage-edx-jwt-refresh-cookie
  JWT_ISSUERS:
  - AUDIENCE: InkocujLikyucsEdwiWatdebrEackmevLakDuifKooshkakWow
    ISSUER: https://courses.stage.edx.org/oauth2
    SECRET_KEY: '{{ "{{" }} .Data.data.JWT_ISSUERS_SECRET_KEY {{ "}}" }}'
  JWT_PUBLIC_SIGNING_JWK_SET: ' {"keys": [{"kid": "lmsstage001", "e": "AQAB", "kty":
    "RSA", "n": "z8QubXfVT8R2ldJ4tb8DTsA3kvfiUM8A74JE-ZyVgzMrBfp9YRpqca8meh05xnaNq2T4w1k3a08U9kgy86OFfeq0GOnq3jiIzmbet7XnQxTCpSrPRDTYhgm4Fin7RHEBgtwhFwhlhN4WlzS0OXBCXwXH-nRvg6bwhfZDWZR_BW3Kmh6eMmtdyQdUkBiRkU-tnlbv00RLi0U4s8AKnjU5K2iRzXDW323jaLdRUYFw3PTDjVQBnbUE3DUi6ZTjCKRwle0qS5NxkKFYeFhEOgs7v-UqFjVbtemWycuD4uiaby-7fP2JiQ6aXi0hkt3uf27RK9pQpF3ToPFv4e9TO68Xtw"}]}'
SECRET_KEY: '{{ .Data.data.SECRET_KEY }}'
SOCIAL_AUTH_EDX_OAUTH2_ISSUER: https://courses.stage.edx.org
SOCIAL_AUTH_EDX_OAUTH2_KEY: N2TQl5cxBbiRaDFxfcpeIcvqaTORcpZt6S4uBrre
SOCIAL_AUTH_EDX_OAUTH2_LOGOUT_URL: https://courses.stage.edx.org/logout
SOCIAL_AUTH_EDX_OAUTH2_SECRET: '{{ "{{" }} .Data.data.SOCIAL_AUTH_EDX_OAUTH2_SECRET {{ "}}" }}'
SOCIAL_AUTH_EDX_OAUTH2_URL_ROOT: https://courses.stage.edx.org
{{ "{{" }} end {{ "}}" }}
