# Config file for automatic testing at travis-ci.org
# To connect a new edX repository to Travis, see
# https://openedx.atlassian.net/wiki/spaces/EdxOps/pages/157464369/How+to+connect+a+repository+to+Travis+CI
#
# Be sure to change the Travis settings in the web UI to enable both
# "Build pushed branches" and "Build pushed pull requests".

language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.8
      env: TOXENV=py38
    - python: 3.5
      env: TOXENV=quality

cache:
  - pip

before_install:
  - pip install --upgrade pip

install:
  - pip install -r requirements/travis.txt

script:
  - tox -v
