---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{cookiecutter.application_name}}
  labels:
    app.kubernetes.io/name: {{cookiecutter.application_name}}
    app.kubernetes.io/instance: {{cookiecutter.application_name}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{cookiecutter.application_name}}
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
