sudo: required
services:
  - docker

language: python
python:
    - 2.7

install:
    - pip install cookiecutter==0.9.0
    - rm -rf /tmp/myxblock-xblock

script:
    - XBLOCK=$(pwd) && cd /tmp/ && echo -e '\n\n\n\n\n' | cookiecutter $XBLOCK
    - cd /tmp/myxblock-xblock && make help && pip install -e .
    - cd /tmp/myxblock-xblock && make dev.build

notifications:
    email: false
